config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "events#index"
  resources :users
  resources :events
  resources :attendances


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :attendee, class_name: "User"
    belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: "creator_id"
  has_many :attendances, foreign_key: "attended_event_id"
  has_many :attendees, through: :attendances, source: :attendee
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :created_events, foreign_key: "creator_id", class_name: "Event"
  has_many :attendances, foreign_key: "attendee_id"
  has_many :attended_events, through: :attendances, source: :attended_event


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
  end
  

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

    before_action :authenticate_user!

    def create
        @event = Event.find(params[:event_id])
        current_user.attendances.create(attended_event: @event)
        redirect_to @event
    end

    def destroy

        @attendance = current_user.attendances.find_by(attended_event_id: params[:id])
        
        if @attendance
            @event =  @attendance.attended_event
            @attendance.destroy
            redirect_to @event
        end
        
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :authenticate_user!

    def index
        @events = Event.all
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.created_events.build(event_params)
        
        if @event.save
            redirect_to events_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @event = Event.find(params[:id])
    end

    private

    def event_params
        params.require(:event).permit(:name, :date, :location)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @events = @user.created_events

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>All Events</h1>

<ul>
  <% @events.each do |event| %>
    <li>
      <%= link_to event.name, event %>
    </li>
  <% end %>
</ul>


<% if user_signed_in? %>

    <%= link_to 'View Profile', user_path(current_user) %>
    <%= link_to "New Event", new_event_path %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
  <%= button_to 'Sign In', new_user_session_path, method: :get  %>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event, local: true do |form| %>    
    <% if @event.errors.any? %>
        <div id = "error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
        </div>

        <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p>Date: <%= @event.date %></p>
<p>Location: <%= @event.location %></p>

<% if user_signed_in? %>
  <% if current_user.attendances.exists?(attended_event_id: @event.id) %>
    <%= button_to 'Cancel Attendance', attendance_path(id: @event.id), method: :delete %>
  <% else %>
    <%= button_to 'Attend Event', attendances_path(event_id: @event.id), method: :post %>
  <% end %>
<% end %>

<h4>Attendees</h4>

<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= link_to attendee.username,  attendee %></li> 
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<p>User: <%= @user.username %></p>
<h3>Events Created by User:</h3>
<ul>
  <% @events.each do |event| %>
    <li><%= link_to event.name, event_path(event) %></li>
  <% end %>
</ul>

<h4>Events Attending</h4>

<ul>
  <% @user.attended_events.each do |a_event| %>
    <li><%= link_to a_event.name,  a_event %></li> 
  <% end %>
</ul>